<?php
/**
 * @file
 * Auto Generated Code - DO NOT EDIT
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.*
 */

/**
 * See LICENSE.TXT for terms of use and copyright.
 */

/**
 * Calculates the edit distance between the two strings.
 *
 * &$target string
 *   The string we're trying to find the closest value to.
 * $test string
 *   The string that we're testing against.
 * $ls integer
 *   The lowest score we've found so far.
 * return integer
 *   The edit distance between the two strings.
 */
function E114($target, $test, $ls) {
  return fiftyone_degrees_edit_distance($target, $test, $ls);
}

/**
 * Returns the details of the devices that are closest to the useragent string provided.
 *
 * $useragent string
 *   The useragent we're trying to find.
 * return array
 *   An array of device details for the closest devices.
 */
function _H114($useragent) {
  $ls = PHP_INT_MAX;
  $dl = array();
  $ua = 'python-requests/0.8.1';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,22118,16074,913, $ua, '15364-17017-17470-18092');
  }
  $ua = 'python-requests/0.10.6';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,22118,16074,913, $ua, '15364-17017-17470-18092');
  }
  $ua = 'python-requests/0.10.8';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,22118,16074,913, $ua, '15364-17017-17470-18092');
  }
  $ua = 'python-requests/0.7.3';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,22118,16074,913, $ua, '15364-17017-17470-18092');
  }
  $ua = 'python-requests/0.11.1';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,22118,16074,913, $ua, '15364-17017-17470-18092');
  }
  $ua = 'python-requests/0.11.2';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,22118,16074,913, $ua, '15364-17017-17470-18092');
  }
  $ua = 'python-requests/0.12.1';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,22118,16074,913, $ua, '15364-17017-17470-18092');
  }
  $ua = 'python-requests/0.9.2';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,22118,16074,913, $ua, '15364-17017-17470-18092');
  }
  $ua = 'python-requests/0.12.0';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,22118,16074,913, $ua, '15364-17017-17470-18092');
  }
  $ua = 'python-requests/0.10.2';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,22118,16074,913, $ua, '15364-17017-17470-18092');
  }
  $ua = 'python-requests/0.13.0';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,22118,16074,913, $ua, '15364-17017-17470-18092');
  }
  $ua = 'python-requests/0.13.1';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,22118,16074,913, $ua, '15364-17017-17470-18092');
  }
  $ua = 'python-requests/0.13.2';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,22118,16074,913, $ua, '15364-17017-17470-18092');
  }
  $ua = 'python-requests/0.8.2';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,22118,16074,913, $ua, '15364-17017-17470-18092');
  }
  $ua = 'python-requests/0.9.3';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,22118,16074,913, $ua, '15364-17017-17470-18092');
  }
  $ua = 'python-requests/0.13.8 CPython/2.7.3 Linux/3.2.21-1.32.6.amzn1.x86_64';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,142808,16074,913, $ua, '15364-18110-17470-18092');
  }
  $ua = 'python-requests/0.14.2 CPython/2.7.3 Linux/3.2.0-32-generic';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,142808,16074,913, $ua, '15364-18110-17470-18092');
  }
  $ua = 'python-requests/0.14.2 CPython/2.7.3 Linux/3.2.0-33-generic';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,142808,16074,913, $ua, '15364-18110-17470-18092');
  }
  $ua = 'python-requests/0.14.2 CPython/2.7.2+ Linux/3.0.0-16-generic-pae';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,142808,16074,913, $ua, '15364-18110-17470-18092');
  }
  $ua = 'python-requests/0.14.2 CPython/2.7.3 Linux/3.2.0-34-generic';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,142808,16074,913, $ua, '15364-18110-17470-18092');
  }
  $ua = 'python-requests/1.1.0 CPython/2.7.3 Linux/3.2.0-31-virtual';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,142808,16074,913, $ua, '15364-18110-17470-18092');
  }
  $ua = 'python-requests/1.1.0 CPython/2.7.3 Linux/3.2.0-36-virtual';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,142808,16074,913, $ua, '15364-18110-17470-18092');
  }
  $ua = 'python-requests/1.1.0 CPython/2.7.3 Linux/3.2.0-4-amd64';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,142808,16074,913, $ua, '15364-18110-17470-18092');
  }
  $ua = 'python-requests/1.1.0 CPython/2.7.3 Linux/3.2.0-34-generic';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,142808,16074,913, $ua, '15364-18110-17470-18092');
  }
  $ua = 'python-requests/1.2.0 CPython/2.6.6 Linux/2.6.32-279.el6.x86_64';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,142808,16074,913, $ua, '15364-18110-17470-18092');
  }
  $ua = 'python-requests/1.1.0 CPython/2.6.5 Linux/2.6.32-346-ec2';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,142808,16074,913, $ua, '15364-18110-17470-18092');
  }
  $ua = 'python-requests/1.2.0 CPython/2.7.3 Linux/3.2.0-29-virtual';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,142808,16074,913, $ua, '15364-18110-17470-18092');
  }
  $ua = 'python-requests/1.0.4 CPython/2.7.3 Linux/3.2.37.1.amd64-smp';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,142808,16074,913, $ua, '15364-18110-17470-18092');
  }
  $ua = 'python-requests/1.2.0 CPython/2.6.5 Linux/2.6.32-350-ec2';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,142808,16074,913, $ua, '15364-18110-17470-18092');
  }
  $ua = 'python-requests/1.2.0 CPython/2.7.4 Linux/3.8.0-21-generic';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,142808,16074,913, $ua, '15364-18110-17470-18092');
  }
  $ua = 'python-requests/1.1.0 CPython/2.7.2 FreeBSD/9.0-RELEASE-p3';
  $ns = E114($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,530516,16074,913, $ua, '15364-18145-17470-18092');
  }
  return $dl;
}
