<?php
/**
 * @file
 * Auto Generated Code - DO NOT EDIT
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.*
 */

/**
 * See LICENSE.TXT for terms of use and copyright.
 */

/**
 * Calculates the edit distance between the two strings.
 *
 * @param &$target string
 *   The string we're trying to find the closest value to.
 * @param $test string
 *   The string that we're testing against.
 * @param $ls integer
 *   The lowest score we've found so far.
 * @return integer
 *   The edit distance between the two strings.
 */
function E115($target, $test, $ls) {
  return fiftyone_degrees_edit_distance($target, $test, $ls);
}

/**
 * Returns the details of the devices that are closest to the useragent string provided.
 *
 * @param $useragent string
 *   The useragent we're trying to find.
 * @return array
 *   An array of device details for the closest devices.
 */
function _H115($useragent) {
  $ls = PHP_INT_MAX;
  $dl = array();
  $ua = 'Pulp/2.1.2 (Mac OS X; http://www.acrylicapps.com/pulp/)';
  $ns = E115($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(47831,126175,431062,913, $ua, '17595-18120-18108-18092');
  }
  $ua = 'Pulp/2.0.1 (Mac OS X; http://www.acrylicapps.com/pulp/)';
  $ns = E115($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(47831,126175,431062,913, $ua, '17595-18120-18108-18092');
  }
  $ua = 'Pulp/2.0 (Mac OS X; http://www.acrylicapps.com/pulp/)';
  $ns = E115($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(47831,126175,431062,913, $ua, '17595-18120-18108-18092');
  }
  $ua = 'Pulp/2.1 (Mac OS X; http://www.acrylicapps.com/pulp/)';
  $ns = E115($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(47831,126175,431062,913, $ua, '17595-18120-18108-18092');
  }
  $ua = 'Pulp/2.5.1 (Mac; http://www.acrylicapps.com/pulp/)';
  $ns = E115($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(47831,126175,431062,913, $ua, '17595-18120-18108-18092');
  }
  $ua = 'Pulp/2.5.3 (Mac; http://www.acrylicapps.com/pulp/)';
  $ns = E115($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(47831,126175,431062,913, $ua, '17595-18120-18108-18092');
  }
  $ua = 'Pulp/2.5.2 (Mac; http://www.acrylicapps.com/pulp/)';
  $ns = E115($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,126175,431062,913, $ua, '15364-18120-18108-18092');
  }
  return $dl;
}
