<?php
/**
 * @file
 * Auto Generated Code - DO NOT EDIT
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.*
 */

/**
 * See LICENSE.TXT for terms of use and copyright.
 */

/**
 * Calculates the edit distance between the two strings.
 *
 * @param &$target string
 *   The string we're trying to find the closest value to.
 * @param $test string
 *   The string that we're testing against.
 * @param $ls integer
 *   The lowest score we've found so far.
 * @return integer
 *   The edit distance between the two strings.
 */
function E90($target, $test, $ls) {
  return fiftyone_degrees_edit_distance($target, $test, $ls);
}

/**
 * Returns the details of the devices that are closest to the useragent string provided.
 *
 * @param $useragent string
 *   The useragent we're trying to find.
 * @return array
 *   An array of device details for the closest devices.
 */
function _H90($useragent) {
  $ls = PHP_INT_MAX;
  $dl = array();
  $ua = 'Spice M6688 MAUI/10A1032MP_ASTRO_W1052 Release/31.12.2010 Browser/Opera Profile/MIDP-2.0 Configuration/CLDC-1.1 Sync/SyncClient1.1 Opera/9.80 (MTK; Nucleus; Opera Mobi/4000; U; en-US) Presto/2.5.28 Version/10.10';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(28546,321856,143787,913, $ua, '18088-22857-18373-18092');
  }
  $ua = 'Browser/Opera Spice M6868n Opera/9.80 (MTK; Nucleus; Opera Mobi/4000; U; en-US) Presto/2.5.28 Version/10.10';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,321856,143787,913, $ua, '15364-22857-18373-18092');
  }
  $ua = 'Browser/Opera Spice M6868n Opera/9.80 (MTK; Nucleus; Opera Mobi/4000; U; hi-IN) Presto/2.5.28 Version/10.10';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,321856,143787,913, $ua, '15364-22857-18373-18092');
  }
  $ua = 'Spice M5100';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,55546,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice QT53';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,55546,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M-5180';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,55546,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M5460';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,55546,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M6450';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,55546,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M5456';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,55546,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M-5455';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,55546,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M5225';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,55546,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M5665';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,55546,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice_M-5400/WapBrowserProfile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,55546,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M5670';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,55546,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M5800';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,55546,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice QT59';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,55546,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M5915 /Spreadtrum/1.0 Release/03.03.2011 Threadx/4.0 Mocor/W10 Browser/NF4.0 Profile/MIDP-2.0Config/CLD-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,55546,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice Mi-354';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,55546,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'SpiceM5600/MTK Release/01.01.2012 Browser/wap2.0 Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1089885,75589,55546,913, $ua, '20247-22835-17470-18092');
  }
  $ua = 'Spice M5600';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1089885,75589,55546,913, $ua, '20247-22835-17470-18092');
  }
  $ua = 'Spice M5600n';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1089885,75589,55546,913, $ua, '20247-22835-17470-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 2.3.4; en-US; Spice_Mi280) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,90496,654678,913, $ua, '15364-5629-24667-18092');
  }
  $ua = 'Spice M5885   Browser/Opera  Opera/9.80 (MTK; U; en-US) Presto/2.5.28 Version/10.10';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,461328,913, $ua, '15364-22835-18272-18092');
  }
  $ua = 'Spice M5885   Browser/Opera  Opera/9.80 (MTK; U; hi-IN) Presto/2.5.28 Version/10.10';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,461328,913, $ua, '15364-22835-18272-18092');
  }
  $ua = 'Spice M5885 Browser/Opera Opera/9.80 (MTK; U; en-US) Presto/2.5.28 Version/10.10';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,75589,461328,913, $ua, '15364-22835-18272-18092');
  }
  $ua = 'Spice M6800 Opera/9.80 (MTK; Nucleus; U; en-US) Presto/2.4.18 Version/10.00';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(326433,321856,325478,913, $ua, '12715-22857-4812-18092');
  }
  $ua = 'Spice M6800  Opera/9.80 (MTK; Nucleus; U; en-US) Presto/2.4.18 Version/10.00';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(326433,321856,325478,913, $ua, '12715-22857-4812-18092');
  }
  $ua = 'Spice M6900 Opera/9.80 (MTK; Nucleus; U; en-US) Presto/2.4.18 Version/10.00';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(407568,321856,325478,913, $ua, '16696-22857-4812-18092');
  }
  $ua = 'Spice M6900  Opera/9.80 (MTK; Nucleus; U; en-US) Presto/2.4.18 Version/10.00';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(407568,321856,325478,913, $ua, '16696-22857-4812-18092');
  }
  $ua = 'Spice_M-5900/WapBrowserProfile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1171535,75589,55546,913, $ua, '23087-22835-17470-18092');
  }
  $ua = 'Spice M6700';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(794842,75589,55546,913, $ua, '16725-22835-17470-18092');
  }
  $ua = 'Spice M5445';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(294196,75589,55546,913, $ua, '16858-22835-17470-18092');
  }
  $ua = 'Spice M5364';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1503661,75589,55546,913, $ua, '23332-22835-17470-18092');
  }
  $ua = 'SpiceM5365/MTK Release/01.01.2012 Browser/wap2.0 Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1223714,75589,55546,913, $ua, '23020-22835-17470-18092');
  }
  $ua = 'Spice M5385';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1503589,75589,55546,913, $ua, '23333-22835-17470-18092');
  }
  $ua = 'Spice M5910';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1306479,75589,55546,913, $ua, '23572-22835-17470-18092');
  }
  $ua = 'SpiceM5665/MTK Release/01.01.2012 Browser/wap2.0 Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1194967,75589,55546,913, $ua, '23022-22835-17470-18092');
  }
  $ua = 'Spice S707/2008.07.09 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138493,75589,55546,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2008.09.26 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138493,75589,55546,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2008.05.29 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138493,75589,55546,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2008.05.16 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138493,75589,55546,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2009.03.03 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138493,75589,55546,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2009.05.31 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138493,75589,55546,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2009.04.28 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138493,75589,55546,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2008.09.02 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138493,75589,55546,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2009.04.10 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138493,75589,55546,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2008.08.20 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138493,75589,55546,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2009.07.15 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138493,75589,55546,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2009.06.29 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138493,75589,55546,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2008.09.27 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138493,75589,55546,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2008.12.03 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138493,75589,55546,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2009.03.25 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138493,75589,55546,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'SpiceM5395/MTK Release/01.01.2012 Browser/wap2.0 Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1289028,75589,55546,913, $ua, '23050-22835-17470-18092');
  }
  $ua = 'Spice M5700';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(243760,75589,55546,913, $ua, '15621-22835-17470-18092');
  }
  $ua = 'Spice M5252';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(444875,75589,55546,913, $ua, '16933-22835-17470-18092');
  }
  $ua = 'Spice M5170';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(240399,75589,55546,913, $ua, '15591-22835-17470-18092');
  }
  $ua = 'Spice M6100';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1454047,75589,55546,913, $ua, '23277-22835-17470-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 2.3.5; en-US; Spice_MI-352) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1311675,90496,654678,913, $ua, '21851-5629-24667-18092');
  }
  $ua = 'Spice M5570';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(253883,75589,55546,913, $ua, '15581-22835-17470-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 2.3.5; en-US; Spice_Mi-351) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1349374,90496,654678,913, $ua, '23016-5629-24667-18092');
  }
  $ua = 'Spice M9000';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(711873,75589,55546,913, $ua, '23376-22835-17470-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 4.0.4; en-US; Spice_Mi-502) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1458538,583223,654678,913, $ua, '23017-18066-24667-18092');
  }
  $ua = 'Spice QT68';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(240255,75589,55546,913, $ua, '15589-22835-17470-18092');
  }
  $ua = 'UP.Browser/5.0/Spice G6550';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44115,27583,52308,913, $ua, '15364-17017-4948-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 2.3.4; en-US; Spice_Mi-320) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1206642,90496,654678,913, $ua, '23463-5629-24667-18092');
  }
  $ua = 'Spice M-940 Gold/WAP2.0 Profile/MIDP2.0 Configuration/CLDC1.1, Spice M-940 Gold/WAP2.0 Profile/MIDP2.0 Configuration/CLDC1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(182187,75589,55546,913, $ua, '16905-22835-17470-18092');
  }
  $ua = 'Spice M-940 Gold/WAP2.0 Profile/MIDP2.0 Configuration/CLDC1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(182187,75589,55546,913, $ua, '16905-22835-17470-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 4.0.4; en-US; Spice_Mi-435) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1312953,583223,654678,913, $ua, '21850-18066-24667-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 4.0.4; en-US; Spice_Mi-502) U2/1.0.0 UCBrowser/8.7.0.315 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1458538,583223,1044974,913, $ua, '23017-18066-24673-18092');
  }
  $ua = 'Spice M5750';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(252292,75589,55546,913, $ua, '15711-22835-17470-18092');
  }
  $ua = 'Spice QT-57/(2010.06.22) S005/WAP2.0 Profile/MIDP2.0 Configuration/CLDC1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(380647,75589,55546,913, $ua, '16856-22835-17470-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; Spice_Mi-355) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1053452,90496,654678,913, $ua, '21039-5629-24667-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 4.0.4; en-US; Spice_Mi-502) U2/1.0.0 UCBrowser/8.6.0.318 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1458538,583223,1028565,913, $ua, '23017-18066-24672-18092');
  }
  $ua = 'Spice S7000/(X)S006/WAP2.0 Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(760950,75589,55546,913, $ua, '16885-22835-17470-18092');
  }
  $ua = 'Spice M5454';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1497301,75589,55546,913, $ua, '16800-22835-17470-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; Spice_Mi-425) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(961428,90496,654678,913, $ua, '21036-5629-24667-18092');
  }
  $ua = 'Spice D88';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(432648,75589,55546,913, $ua, '17118-22835-17470-18092');
  }
  $ua = 'Spice D88/WAP2.0';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(432648,75589,55546,913, $ua, '17118-22835-17470-18092');
  }
  $ua = 'Spice_M6400/WapBrowserConfiguration2.0/MIDP2.0/CLDC1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(287477,75589,55546,913, $ua, '12791-22835-17470-18092');
  }
  $ua = 'Spice M5262';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1247417,75589,55546,913, $ua, '16778-22835-17470-18092');
  }
  $ua = 'Spice S580';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(437061,75589,55546,913, $ua, '16995-22835-17470-18092');
  }
  $ua = 'Spice/1.0/QT-68/Obigo Browser/Q03C Browser/Q03C MMS/1.0/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(240255,75589,100029,913, $ua, '15589-22835-3807-18092');
  }
  $ua = 'Spice S950 NF-Browser/3.3 Openwave-MMS/4.5 IA-Java/1.0 Profile/MIDP2.0/CLDC1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(355664,75589,37296,913, $ua, '14298-22835-3601-18092');
  }
  $ua = 'Spice S710';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(437709,75589,55546,913, $ua, '16989-22835-17470-18092');
  }
  $ua = 'Spice S5330';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(446992,75589,55546,913, $ua, '16986-22835-17470-18092');
  }
  $ua = 'Spice S5420';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(447064,75589,55546,913, $ua, '16924-22835-17470-18092');
  }
  $ua = 'Spice S650/KAA736_0.90.626 Nucleus/1.0 MTK/6223 Release/06.26.2007 Browser/Teleca_obigo Profile/MIDP-1.0 Configuration/CLDC-1.0';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(436630,321856,55546,913, $ua, '17061-22857-17470-18092');
  }
  $ua = 'Spice S820';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(444803,75589,55546,913, $ua, '17068-22835-17470-18092');
  }
  $ua = 'Spice S705';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(446920,75589,55546,913, $ua, '16912-22835-17470-18092');
  }
  return $dl;
}
