<?php
/**
 * @file
 * Auto Generated Code - DO NOT EDIT
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.*
 */

/**
 * See LICENSE.TXT for terms of use and copyright.
 */

/**
 * Calculates the edit distance between the two strings.
 *
 * &$target string
 *   The string we're trying to find the closest value to.
 * $test string
 *   The string that we're testing against.
 * $ls integer
 *   The lowest score we've found so far.
 * return integer
 *   The edit distance between the two strings.
 */
function E97($target, $test, $ls) {
  return fiftyone_degrees_edit_distance($target, $test, $ls);
}

/**
 * Returns the details of the devices that are closest to the useragent string provided.
 *
 * $useragent string
 *   The useragent we're trying to find.
 * return array
 *   An array of device details for the closest devices.
 */
function _H97($useragent) {
  $ls = PHP_INT_MAX;
  $dl = array();
  $ua = 'W3C_Validator/1.1';
  $ns = E97($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,298022,16074,913, $ua, '15364-7480-17470-18092');
  }
  $ua = 'W3C_Validator/1.432.2.22';
  $ns = E97($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,298022,16074,913, $ua, '15364-7480-17470-18092');
  }
  $ua = 'W3C_Validator/1.2';
  $ns = E97($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,298022,16074,913, $ua, '15364-7480-17470-18092');
  }
  $ua = 'W3C_Validator/1.3';
  $ns = E97($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,298022,16074,913, $ua, '15364-7480-17470-18092');
  }
  $ua = 'W3C_Validator/1.3 http://validator.w3.org/services';
  $ns = E97($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(53173,298022,16074,913, $ua, '15364-7480-17470-18092');
  }
  return $dl;
}
